[config]
default_to_workspace = false
skip_core_tasks = true

# Global tasks
[tasks.clean]
script_runner = "@duckscript"
script = '''
echo "Cleaning all packages..."
exec --fail-on-error cargo clean
'''

[tasks.unit-tests]
script_runner = "@duckscript"
script = '''
echo "Running unit tests for all packages..."
exec --fail-on-error cargo test
'''

[tasks.check]
description = "Runs rustfmt and clippy checks without applying any fix"
dependencies = ["check-clippy", "check-rustfmt"]

[tasks.check-rustfmt]
description = "Runs rustfmt checks without applying any fix"
install_crate = "rustfmt"
command = "cargo"
args = ["fmt", "--all", "--", "--check"]

[tasks.check-clippy]
description = "Runs clippy checks without applying any fix"
install_crate = "clippy"
command = "cargo"
args = ["clippy", "--all-targets", "--", "--no-deps", "-Dwarnings"]


[tasks.build-all]
script_runner = "@duckscript"
script = '''
echo "Building all packages..."
exec --fail-on-error cargo make --makefile golem-llm/Makefile.toml build-all
'''

[tasks.build-test-components]
script_runner = "@duckscript"
script = '''
echo "Building test components..."
exec --fail-on-error cargo make --makefile golem-llm/Makefile.toml build-test-components
'''

[tasks.release-build-all]
script_runner = "@duckscript"
script = '''
echo "Building all packages in release mode..."
exec --fail-on-error cargo make --makefile golem-llm/Makefile.toml release-build-all
'''
