// Generated by `wit-bindgen` 0.41.0. DO NOT EDIT!
// Options used:
//   * runtime_path: "wit_bindgen_rt"
//   * with "golem:video/video@1.0.0" = "golem_video::golem::video::video"
//   * generate_unused_types
use golem_video::golem::video::video as __with_name0;
#[cfg(target_arch = "wasm32")]
#[unsafe(
    link_section = "component-type:wit-bindgen:0.41.0:golem:video-kling@1.0.0:video-library:encoded world"
)]
#[doc(hidden)]
#[allow(clippy::octal_escapes)]
pub static __WIT_BINDGEN_COMPONENT_TYPE: [u8; 1054] = *b"\
\0asm\x0d\0\x01\0\0\x19\x16wit-component-encoding\x04\0\x07\x9a\x07\x01A\x02\x01\
A\x02\x01B+\x01q\x06\x0dinvalid-input\x01s\0\x13unsupported-feature\x01s\0\x0equ\
ota-exceeded\0\0\x11generation-failed\x01s\0\x09cancelled\0\0\x0einternal-error\x01\
s\0\x04\0\x0bvideo-error\x03\0\0\x01p}\x01q\x02\x03url\x01s\0\x05bytes\x01\x02\0\
\x04\0\x0amedia-data\x03\0\x03\x01ks\x01r\x02\x04data\x04\x06prompt\x05\x04\0\x0f\
reference-image\x03\0\x06\x01q\x02\x04text\x01s\0\x05image\x01\x07\0\x04\0\x0bme\
dia-input\x03\0\x08\x01m\x04\x06square\x08portrait\x09landscape\x06cinema\x04\0\x0c\
aspect-ratio\x03\0\x0a\x01m\x04\x02sd\x02hd\x03fhd\x03uhd\x04\0\x0aresolution\x03\
\0\x0c\x01r\x02\x03keys\x05values\x04\0\x02kv\x03\0\x0e\x01kw\x01kv\x01k\x0b\x01\
k\x0d\x01k\x7f\x01p\x0f\x01r\x0b\x0fnegative-prompt\x05\x04seed\x10\x09scheduler\
\x05\x0eguidance-scale\x11\x0caspect-ratio\x12\x10duration-seconds\x11\x0aresolu\
tion\x13\x05model\x05\x0cenable-audio\x14\x0eenhance-prompt\x14\x10provider-opti\
ons\x15\x04\0\x11generation-config\x03\0\x16\x01k\x02\x01ky\x01r\x07\x03uri\x05\x0c\
base64-bytes\x18\x09mime-types\x05width\x19\x06height\x19\x03fps\x11\x10duration\
-seconds\x11\x04\0\x05video\x03\0\x1a\x01q\x04\x07pending\0\0\x07running\0\0\x09\
succeeded\0\0\x06failed\x01s\0\x04\0\x0ajob-status\x03\0\x1c\x01p\x1b\x01k\x1e\x01\
k\x15\x01r\x03\x06status\x1d\x06videos\x1f\x08metadata\x20\x04\0\x0cvideo-result\
\x03\0!\x01j\x01s\x01\x01\x01@\x02\x05input\x09\x06config\x17\0#\x04\0\x08genera\
te\x01$\x01j\x01\"\x01\x01\x01@\x01\x06job-ids\0%\x04\0\x04poll\x01&\x01@\x01\x06\
job-ids\0#\x04\0\x06cancel\x01'\x04\0\x17golem:video/video@1.0.0\x05\0\x04\0%gol\
em:video-kling/video-library@1.0.0\x04\0\x0b\x13\x01\0\x0dvideo-library\x03\0\0\0\
G\x09producers\x01\x0cprocessed-by\x02\x0dwit-component\x070.227.1\x10wit-bindge\
n-rust\x060.41.0";
#[inline(never)]
#[doc(hidden)]
pub fn __link_custom_section_describing_imports() {
    wit_bindgen_rt::maybe_link_cabi_realloc();
}
