package golem:web-search-google@1.0.0;

interface types {
  use golem:web-search@1.0.0/types.{search-params, search-result, search-metadata, search-error};
}

interface web-search {
  use golem:web-search@1.0.0/web-search;
}

world web-search-google-library {
    export web-search;
} 