// Generated by `wit-bindgen` 0.36.0. DO NOT EDIT!
// Options used:
//   * runtime_path: "wit_bindgen_rt"
//   * with "golem:llm/llm@1.0.0" = "golem_llm::golem::llm::llm"
//   * generate_unused_types
use golem_llm::golem::llm::llm as __with_name0;
#[cfg(target_arch = "wasm32")]
#[link_section = "component-type:wit-bindgen:0.36.0:golem:llm-grok@1.0.0:llm-library:encoded world"]
#[doc(hidden)]
pub static __WIT_BINDGEN_COMPONENT_TYPE: [u8; 1750] = *b"\
\0asm\x0d\0\x01\0\0\x19\x16wit-component-encoding\x04\0\x07\xd4\x0c\x01A\x02\x01\
A\x02\x01BO\x01m\x04\x04user\x09assistant\x06system\x04tool\x04\0\x04role\x03\0\0\
\x01m\x06\x0finvalid-request\x15authentication-failed\x13rate-limit-exceeded\x0e\
internal-error\x0bunsupported\x07unknown\x04\0\x0aerror-code\x03\0\x02\x01m\x06\x04\
stop\x06length\x0atool-calls\x0econtent-filter\x05error\x05other\x04\0\x0dfinish\
-reason\x03\0\x04\x01m\x03\x03low\x04high\x04auto\x04\0\x0cimage-detail\x03\0\x06\
\x01k\x07\x01r\x02\x03urls\x06detail\x08\x04\0\x09image-url\x03\0\x09\x01p}\x01r\
\x03\x04data\x0b\x09mime-types\x06detail\x08\x04\0\x0aimage-data\x03\0\x0c\x01q\x02\
\x03url\x01\x0a\0\x04data\x01\x0d\0\x04\0\x0cimage-source\x03\0\x0e\x01q\x02\x04\
text\x01s\0\x05image\x01\x0f\0\x04\0\x0ccontent-part\x03\0\x10\x01ks\x01p\x11\x01\
r\x03\x04role\x01\x04name\x12\x07content\x13\x04\0\x07message\x03\0\x14\x01r\x03\
\x04names\x0bdescription\x12\x11parameters-schemas\x04\0\x0ftool-definition\x03\0\
\x16\x01r\x03\x02ids\x04names\x0earguments-jsons\x04\0\x09tool-call\x03\0\x18\x01\
ky\x01r\x04\x02ids\x04names\x0bresult-jsons\x11execution-time-ms\x1a\x04\0\x0cto\
ol-success\x03\0\x1b\x01r\x04\x02ids\x04names\x0derror-messages\x0aerror-code\x12\
\x04\0\x0ctool-failure\x03\0\x1d\x01q\x02\x07success\x01\x1c\0\x05error\x01\x1e\0\
\x04\0\x0btool-result\x03\0\x1f\x01r\x02\x03keys\x05values\x04\0\x02kv\x03\0!\x01\
kv\x01ps\x01k$\x01p\x17\x01p\"\x01r\x07\x05models\x0btemperature#\x0amax-tokens\x1a\
\x0estop-sequences%\x05tools&\x0btool-choice\x12\x10provider-options'\x04\0\x06c\
onfig\x03\0(\x01r\x03\x0cinput-tokens\x1a\x0doutput-tokens\x1a\x0ctotal-tokens\x1a\
\x04\0\x05usage\x03\0*\x01k\x05\x01k+\x01r\x05\x0dfinish-reason,\x05usage-\x0bpr\
ovider-id\x12\x09timestamp\x12\x16provider-metadata-json\x12\x04\0\x11response-m\
etadata\x03\0.\x01p\x19\x01r\x04\x02ids\x07content\x13\x0atool-calls0\x08metadat\
a/\x04\0\x11complete-response\x03\01\x01r\x03\x04code\x03\x07messages\x13provide\
r-error-json\x12\x04\0\x05error\x03\03\x01q\x03\x07message\x012\0\x0ctool-reques\
t\x010\0\x05error\x014\0\x04\0\x0achat-event\x03\05\x01k\x13\x01k0\x01r\x02\x07c\
ontent7\x0atool-calls8\x04\0\x0cstream-delta\x03\09\x01q\x03\x05delta\x01:\0\x06\
finish\x01/\0\x05error\x014\0\x04\0\x0cstream-event\x03\0;\x04\0\x0bchat-stream\x03\
\x01\x01h=\x01p<\x01k?\x01@\x01\x04self>\0\xc0\0\x04\0\x1c[method]chat-stream.ge\
t-next\x01A\x01@\x01\x04self>\0?\x04\0%[method]chat-stream.blocking-get-next\x01\
B\x01p\x15\x01@\x02\x08messages\xc3\0\x06config)\06\x04\0\x04send\x01D\x01o\x02\x19\
\x20\x01p\xc5\0\x01@\x03\x08messages\xc3\0\x0ctool-results\xc6\0\x06config)\06\x04\
\0\x08continue\x01G\x01i=\x01@\x02\x08messages\xc3\0\x06config)\0\xc8\0\x04\0\x06\
stream\x01I\x04\0\x13golem:llm/llm@1.0.0\x05\0\x04\0\x20golem:llm-grok/llm-libra\
ry@1.0.0\x04\0\x0b\x11\x01\0\x0bllm-library\x03\0\0\0G\x09producers\x01\x0cproce\
ssed-by\x02\x0dwit-component\x070.220.0\x10wit-bindgen-rust\x060.36.0";
#[inline(never)]
#[doc(hidden)]
pub fn __link_custom_section_describing_imports() {
    wit_bindgen_rt::maybe_link_cabi_realloc();
}
